config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'home#index' 
    
  resources :patients do
    resources :appointments
  end
  resources :appointments do
    member do
      patch :update_status
    end
  end  
  resources :appointments
  resources :doctors
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @patients = Patient.all
    @doctors = Doctor.all
    @appointments = Appointment.where(status: :completed)  
    
    @patient = Patient.first 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/home/index.html.erb
<h1>Welcome to the Daycrop Hospital</h1>

<div class="dashboard-container">

  <div class="card">
    <h2>Doctors (<%= Doctor.count %>)</h2>
    <% if Doctor.exists? %>
      <%= link_to 'View All Doctors', doctors_path %>
    <% else %>
      <p>No doctors available.</p>
      <%= link_to 'Add New Doctor', new_doctor_path%>
    <% end %>
  </div>

  <div class="card">
    <h2>Patients (<%= Patient.count %>)</h2>
    <% if Patient.exists? %>
      <%= link_to 'View All Patients', patients_path %>
    <% else %>
      <p>No patients available.</p>
      <%= link_to 'Add New Patient', new_patient_path %>
    <% end %>
  </div>

  <div class="card">
    <h2>Appointments (<%= Appointment.count %>)</h2>
    <% if Appointment.exists? %>
      <%= link_to 'View All Appointments', appointments_path %>
    <% else %>
      <p>No appointments booked.</p>
      <%= link_to 'Book an Appointment', new_appointment_path %>
    <% end %>
  </div>


</div>